# Generated by Django 5.2.8 on 2026-01-14 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rubric_alter_bb_options_alter_bb_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamKiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название киоска')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('is_open', models.BooleanField(default=True, verbose_name='Открыт')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО родителя')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
            ],
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ('name',), 'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('flavor', models.CharField(max_length=120, verbose_name='Вкус')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ice_creams', to='bboard.icecreamkiosk', verbose_name='Киоск')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО ребёнка')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bboard.parent', verbose_name='Родитель')),
            ],
        ),
    ]
