# Generated by Django 5.2.8 on 2026-01-14 12:45

import bboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_icecreamkiosk_parent_alter_rubric_options_icecream_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.PositiveIntegerField(validators=[bboard.validators.non_negative], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[bboard.validators.non_negative], verbose_name='Цена'),
        ),
    ]
